export const colors = new Map([
  ['Stile', '#A1A1A1'],
  ['Dark', '#A1A1A1'],
  ['Rock', '#A1A1A1'],
  ['Grass', '#70A83B'],
  ['Bug', '#70A83B'],
  ['Ice', '#A2CFF0'],
  ['Water', '#A2CFF0'],
  ['Fire', '#F76545'],
  ['Fighting', '#F76545'],
  ['Dragon', '#F76545'],
  ['Normal', '#76AABD'],
  ['Gosth', '#76AABD'],
  ['Ghost', '#A974BC'],
  ['Psychic', '#A974BC'],
  ['Fairy', '#A974BC'],
  ['Poison', '#A974BC'],
  ['Ground', '#9B897B'],
  ['Electric', '#F7C545'],
])

export const backgrounds = new Map([
  ['Stile', '#A1A1A1'],
  ['Dark', '#A1A1A1'],
  ['Rock', '#A1A1A1'],
  ['Grass', 'green'],
  ['Bug', 'green'],
  ['Ice', 'blue'],
  ['Water', 'blue'],
  ['Fire', 'red'],
  ['Fighting', 'red'],
  ['Dragon', 'red'],
  ['Normal', '#76AABD'],
  ['Gosth', '#76AABD'],
  ['Ghost', 'pink'],
  ['Psychic', 'pink'],
  ['Fairy', 'pink'],
  ['Poison', 'pink'],
  ['Ground', 'green'],
  ['Electric', 'yellow'],
])

export const POKEMON_TYPES = [
  'Normal',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Ice',
  'Poison',
  'Psychic',
  'Ghost',
  'Fairy',
]
